apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orderflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - api/migration-job.yaml
  - api/deployment.yaml
  - api/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: orderflow
