apiVersion: v1
kind: Service
metadata:
  name: orderflow-web
  namespace: orderflow
spec:
  type: ClusterIP
  selector:
    app: orderflow-web
  ports:
    - name: http
      port: 80
      targetPort: http
